// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // ChannelEmail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class ChannelEmail
    {
        public int Id { get; set; } // Id (Primary key)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string Message { get; set; } // Message
        public string AccessToken { get; set; } // AccessToken
        public long? ExpiresInSeconds { get; set; } // ExpiresInSeconds
        public string IdToken { get; set; } // IdToken
        public System.DateTime? Issued { get; set; } // Issued
        public System.DateTime? IssuedUtc { get; set; } // IssuedUtc
        public string RefreshToken { get; set; } // RefreshToken
        public string Scope { get; set; } // Scope
        public string TokenType { get; set; } // TokenType
        public System.DateTime? LastSyncedDate { get; set; } // LastSyncedDate

        public ChannelEmail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
