// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // ChannelMagento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class ChannelMagentoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ChannelMagento>
    {
        public ChannelMagentoConfiguration()
            : this("dbo")
        {
        }

        public ChannelMagentoConfiguration(string schema)
        {
            ToTable(schema + ".ChannelMagento");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").IsRequired().HasColumnType("datetime");
            Property(x => x.Username).HasColumnName(@"Username").IsRequired().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.Password).HasColumnName(@"Password").IsRequired().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.Host).HasColumnName(@"Host").IsRequired().HasColumnType("nvarchar").HasMaxLength(255);
            Property(x => x.StoreId).HasColumnName(@"StoreId").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.LastSyncedDateTicket).HasColumnName(@"LastSyncedDate_Ticket").IsOptional().HasColumnType("datetime");
            Property(x => x.LastSyncedDateMessage).HasColumnName(@"LastSyncedDate_Message").IsOptional().HasColumnType("datetime");
            Property(x => x.Message).HasColumnName(@"Message").IsOptional().HasColumnType("nvarchar");
            Property(x => x.TimeZoneDisplayName).HasColumnName(@"TimeZoneDisplayName").IsRequired().HasColumnType("nvarchar").HasMaxLength(255);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
