// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // Connection
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class Connection
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserChannelSource { get; set; } // UserChannelSource
        public int UserChannelTarget { get; set; } // UserChannelTarget
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public System.DateTime? LastSyncedDate { get; set; } // LastSyncedDate
        public System.DateTime? NextSyncedDate { get; set; } // NextSyncedDate
        public Shared.Enums.ConnectionStatus Status { get; set; } // Status
        public int Counter { get; set; } // Counter
        public string Message { get; set; } // Message
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<TicketEbay> TicketEbays { get; set; } // TicketEbay.FK_TicketEbay_Connection_ConnectionId
        public virtual System.Collections.Generic.ICollection<TicketEmail> TicketEmails { get; set; } // TicketEmail.FK_TicketEmail_Connection_ConnectionId
        public virtual System.Collections.Generic.ICollection<TicketMagento> TicketMagentoes { get; set; } // TicketMagento.FK_TicketMagento_Connection_ConnectionId

        // Foreign keys
        public virtual UserChannel UserChannel_UserChannelSource { get; set; } // FK_Connection_UserChannel_Id_Source
        public virtual UserChannel UserChannel_UserChannelTarget { get; set; } // FK_Connection_UserChannel_Id_Target

        public Connection()
        {
            IsActive = true;
            TicketEbays = new System.Collections.Generic.List<TicketEbay>();
            TicketEmails = new System.Collections.Generic.List<TicketEmail>();
            TicketMagentoes = new System.Collections.Generic.List<TicketMagento>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
