// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // Connection
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class ConnectionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Connection>
    {
        public ConnectionConfiguration()
            : this("dbo")
        {
        }

        public ConnectionConfiguration(string schema)
        {
            ToTable(schema + ".Connection");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserChannelSource).HasColumnName(@"UserChannelSource").IsRequired().HasColumnType("int");
            Property(x => x.UserChannelTarget).HasColumnName(@"UserChannelTarget").IsRequired().HasColumnType("int");
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").IsRequired().HasColumnType("datetime");
            Property(x => x.LastSyncedDate).HasColumnName(@"LastSyncedDate").IsOptional().HasColumnType("datetime");
            Property(x => x.NextSyncedDate).HasColumnName(@"NextSyncedDate").IsOptional().HasColumnType("datetime");
            Property(x => x.Status).HasColumnName(@"Status").IsRequired().HasColumnType("int");
            Property(x => x.Counter).HasColumnName(@"Counter").IsRequired().HasColumnType("int");
            Property(x => x.Message).HasColumnName(@"Message").IsOptional().HasColumnType("nvarchar");
            Property(x => x.IsActive).HasColumnName(@"IsActive").IsRequired().HasColumnType("bit");

            // Foreign keys
            HasRequired(a => a.UserChannel_UserChannelSource).WithMany(b => b.UserChannelSource).HasForeignKey(c => c.UserChannelSource).WillCascadeOnDelete(false); // FK_Connection_UserChannel_Id_Source
            HasRequired(a => a.UserChannel_UserChannelTarget).WithMany(b => b.UserChannelTarget).HasForeignKey(c => c.UserChannelTarget).WillCascadeOnDelete(false); // FK_Connection_UserChannel_Id_Target
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
