// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // MessageEbayMagento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class MessageEbayMagentoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MessageEbayMagento>
    {
        public MessageEbayMagentoConfiguration()
            : this("dbo")
        {
        }

        public MessageEbayMagentoConfiguration(string schema)
        {
            ToTable(schema + ".MessageEbayMagento");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdEbay).HasColumnName(@"IdEbay").IsRequired().HasColumnType("int");
            Property(x => x.IdMagento).HasColumnName(@"IdMagento").IsRequired().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.MessageEbay).WithMany(b => b.MessageEbayMagentoes).HasForeignKey(c => c.IdEbay).WillCascadeOnDelete(false); // FK_MessageEbayMagento_MessageEbay_IdEbay
            HasRequired(a => a.MessageMagento).WithMany(b => b.MessageEbayMagentoes).HasForeignKey(c => c.IdMagento).WillCascadeOnDelete(false); // FK_MessageEbayMagento_MessageMagento_IdMagento
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
