// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // MessageEbay
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class MessageEbay
    {
        public int Id { get; set; } // Id (Primary key)
        public string EbayId { get; set; } // EbayId (length: 255)
        public string SenderId { get; set; } // SenderId (length: 255)
        public string SenderEmail { get; set; } // SenderEmail (length: 255)
        public int TicketId { get; set; } // TicketId
        public string Message { get; set; } // Message
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public System.DateTime? LastModifiedDate { get; set; } // LastModifiedDate
        public string Note { get; set; } // Note
        public System.DateTime? LastSynchronizedDate { get; set; } // LastSynchronizedDate
        public Shared.Enums.SyncStatus SyncStatus { get; set; } // SyncStatus
        public string SyncErrorMessage { get; set; } // SyncErrorMessage

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<MessageEbayMagento> MessageEbayMagentoes { get; set; } // MessageEbayMagento.FK_MessageEbayMagento_MessageEbay_IdEbay

        // Foreign keys
        public virtual TicketEbay TicketEbay { get; set; } // FK_MessageEbay_TicketEbay_TicketId

        public MessageEbay()
        {
            MessageEbayMagentoes = new System.Collections.Generic.List<MessageEbayMagento>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
