// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // TicketEmailMagento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class TicketEmailMagentoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TicketEmailMagento>
    {
        public TicketEmailMagentoConfiguration()
            : this("dbo")
        {
        }

        public TicketEmailMagentoConfiguration(string schema)
        {
            ToTable(schema + ".TicketEmailMagento");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdEmail).HasColumnName(@"IdEmail").IsRequired().HasColumnType("int");
            Property(x => x.IdMagento).HasColumnName(@"IdMagento").IsRequired().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.TicketEmail).WithMany(b => b.TicketEmailMagentoes).HasForeignKey(c => c.IdEmail).WillCascadeOnDelete(false); // FK_TicketEmailMagento_TicketEmail_IdEmail
            HasRequired(a => a.TicketMagento).WithMany(b => b.TicketEmailMagentoes).HasForeignKey(c => c.IdMagento).WillCascadeOnDelete(false); // FK_TicketEmailMagento_TicketMagento_IdMagento
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
