// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // TicketEmailMagento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class TicketEmailMagento
    {
        public int Id { get; set; } // Id (Primary key)
        public int IdEmail { get; set; } // IdEmail
        public int IdMagento { get; set; } // IdMagento

        // Foreign keys
        public virtual TicketEmail TicketEmail { get; set; } // FK_TicketEmailMagento_TicketEmail_IdEmail
        public virtual TicketMagento TicketMagento { get; set; } // FK_TicketEmailMagento_TicketMagento_IdMagento

        public TicketEmailMagento()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
