// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class User
    {
        public int Id { get; set; } // Id (Primary key)
        public string Firstname { get; set; } // Firstname (length: 255)
        public string LastName { get; set; } // LastName (length: 255)
        public string Account { get; set; } // Account (length: 255)
        public string Password { get; set; } // Password (length: 255)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<UserChannel> UserChannels { get; set; } // UserChannel.FK_UserChannel_User_UserId

        public User()
        {
            UserChannels = new System.Collections.Generic.List<UserChannel>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
