// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // UserChannel
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class UserChannelConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserChannel>
    {
        public UserChannelConfiguration()
            : this("dbo")
        {
        }

        public UserChannelConfiguration(string schema)
        {
            ToTable(schema + ".UserChannel");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserId").IsRequired().HasColumnType("int");
            Property(x => x.ChannelId).HasColumnName(@"ChannelId").IsRequired().HasColumnType("int");
            Property(x => x.ChannelType).HasColumnName(@"ChannelType").IsRequired().HasColumnType("int");
            Property(x => x.IsActive).HasColumnName(@"IsActive").IsRequired().HasColumnType("bit");

            // Foreign keys
            HasRequired(a => a.User).WithMany(b => b.UserChannels).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_UserChannel_User_UserId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
