// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace SmartHub.Repositories.Entities
{

    // UserChannel
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public partial class UserChannel
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public int ChannelId { get; set; } // ChannelId
        public Shared.Enums.ChannelType ChannelType { get; set; } // ChannelType
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Connection> UserChannelSource { get; set; } // Connection.FK_Connection_UserChannel_Id_Source
        public virtual System.Collections.Generic.ICollection<Connection> UserChannelTarget { get; set; } // Connection.FK_Connection_UserChannel_Id_Target

        // Foreign keys
        public virtual User User { get; set; } // FK_UserChannel_User_UserId

        public UserChannel()
        {
            IsActive = true;
            UserChannelSource = new System.Collections.Generic.List<Connection>();
            UserChannelTarget = new System.Collections.Generic.List<Connection>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
